export default {
  userName: "Username",
  email: "Email",
  password: "Password",
  address: "Address",
  phone: "Phone",
  role: "Role",
  bankAccountNumber: "Bank Account Number",
  bankAccountUserName: "Bank Account User Name",
  bankName: "Bank Name",
  easyPaisaAccountNumber: "Easy Paisa Account Number",
  paypalEmail: "Paypal Email",
  selectRole: "Select Role",
  selectBankName: "Select Bank Name",
  title: "Profile",
  auctionsWon: "Auctions Won",
  moneySpent: "Money Spent",
  unpaidCommissions: "Unpaid Commissions",
};
